-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib n
  | n == 0    = 0
  | n == 1    = 1
  | otherwise = fib(n - 1) + fib(n - 2)

fibs = map fib [1..]
lt4m = takeWhile(< 4000000) fibs
evenFibs = [ n | n <- lt4m, n `mod` 2 == 0 ]
solve = sum evenFibs
